[platformio]
src_dir = esp32-birdnet-mic

[env:m5stack-atom-voices3r]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38/platform-espressif32.zip
board = m5stack-atoms3r
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -DM5STACK_ATOM_VOICES3R=1
lib_deps =
  tzapu/WiFiManager @ ^2.0.17
  knolleary/PubSubClient @ ^2.8
